# Generated by Django 3.1.1 on 2020-09-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
